### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by xaviola912** [melsen888/are-you-se-Riyus-#1]
Add refresh function please

**Comment by melsen888** [comment]
code:
<img width="254" alt="blocks" src="https://github.com/melsen888/are-you-se-Riyus-/assets/97205073/db5e5328-0519-426b-aaaf-f9f8f8f62c72">

The second text box from the left is the reload function
<img src="https://github.com/melsen888/are-you-se-Riyus-/assets/97205073/b1f7b750-3fd4-4657-a2ba-c3228cdd438b" width="300">
